version: '3'
services:
    ordering:
        build: 
            context: ./Ordering
            args:
                buildno: 1
        volumes:
            - /home/ec2-user/SEManagement2019/hotBurger/log.json:/home/ec2-user/SEManagement2019/hotBurger/log.json
            - /home/ec2-user/SEManagement2019/hotBurger/orderType.json:/home/ec2-user/SEManagement2019/hotBurger/orderType.json
        ports:
            - "80:80"
        expose:
            - "80"
    monitoring:

    monitoringService:
        build: 
            context: ./Monitoring
            args:
                buildno: 1
        volumes:
            - /home/ec2-user/SEManagement2019/hotBurger/orderType.json:/home/ec2-user/SEManagement2019/hotBurger/orderType.json
            - /home/ec2-user/SEManagement2019/hotBurger/log.json:/home/ec2-user/SEManagement2019/hotBurger/log.json

        ports:
            - "8080:8080"
        expose:
            - "8080"
    cache:
        image: "redis:latest"

volumes:
    logs:
    orders:
